DB構築 Migration Products関連
quest-academia/qa-rails-ec-training pull request #11
Opened 2020-12-11 18:14 UTC by git-ryou2405

## 作業内容
以下、Product関連のモデルを作成
・Category
・SaleStatus
・ProductStatus
・Product
・Purchase

※ほとんどのカラムにpresence: trueを実施。
（商品モデルのdescriptionは未実施）

※rails consoleから全てのテーブルにデータ登録しリレーション が問題なさそうか確認実施しました。

例：（データ登録後）
>user = User.find(1)
>user.products

## 対象ページ・箇所

## 重点的に見てほしいところ(不安なところ)
Purchaseの以下２つのカラムだけ、定義が不明な状況でしたのでnull: false未実施です。
・order_date
・purchase_date

## 解決できなかった点

2020-12-12 15:39 UTC, yuki-tachi0219 requested changes
すごくいい感じです！
クラス名を単数形にしてくださるあたり、かなり作り慣れていますね 👍 
2箇所修正お願いします 🙏

2020-12-12 15:39 UTC, yuki-tachi0219 commented on db/migrate/20201211170656_create_purchases.rb
> +      t.integer :purchase_quanity, null: false
purchase_quanity ← typo!

2020-12-12 15:39 UTC, yuki-tachi0219 commented on app/models/purchase.rb
> +  validates :purchase_price, :purchase_quanity, :purchase_company, presence: true
purchase_quanity ← typo!

2020-12-13 02:19 UTC, git-ryou2405 commented on db/migrate/20201211170656_create_purchases.rb
> +      t.integer :purchase_quanity, null: false
ありがとうございます！🙇‍♂️
修正しました！

2020-12-13 02:19 UTC, git-ryou2405 commented on app/models/purchase.rb
> +  validates :purchase_price, :purchase_quanity, :purchase_company, presence: true
修正しました！

2020-12-13 14:42 UTC, yuki-tachi0219 approved these changes
![LGTM](https://user-images.githubusercontent.com/53440378/102015100-d9035980-3d9c-11eb-9279-b8204b3d2368.png)

2020-12-13 14:42 UTC, merged