TOP画面（ログイン後）
quest-academia/qa-rails-ec-training pull request #15
Opened 2020-12-15 09:56 UTC by git-ryou2405

## 作業内容
・StaticPagesコントローラーを作成（Action: home）
・URL: / (root_path)を設定
・header, footerを部分テンプレートで分けて表示
・main部分をhome.html.erbに記述し、ifでログイン前後を分岐
　（一時的に、@login_flagを定義）

・apprication.cssをscssに変更し、cssを記述
　※cssにbootstrapを使用していた為、gem bootstrapをインストール
　※@import "bootstrap";でインポート

## 対象ページ・箇所

## 重点的に見てほしいところ(不安なところ)

## 解決できなかった点

2020-12-15 14:49 UTC, yuki-tachi0219 requested changes
すごくいい感じです！
軽微な修正ですが、一点だけご対応お願いします 🙏

2020-12-15 14:49 UTC, yuki-tachi0219 commented on app/helpers/static_pages_helper.rb
> +module StaticPagesHelper
このヘルパーは今後使わなさそうなので、消しておいてください 🌀

2020-12-15 15:32 UTC, git-ryou2405 commented on app/helpers/static_pages_helper.rb
> +module StaticPagesHelper
削除しました！

2020-12-16 05:16 UTC, yuki-tachi0219 approved these changes
![LGTM](https://user-images.githubusercontent.com/53440378/102308087-3e2b9a80-3fa9-11eb-9b50-2162dc208335.png)

2020-12-16 05:17 UTC, merged