フロント購入完了画面 / タイトルを動的に対応 / CSS切り出し
quest-academia/qa-rails-ec-training pull request #16
Opened 2020-12-18 10:43 UTC by TAKO-zhangyu

## 作業内容

- フロント購入完了画面を実装
- provide, yieldメソッドを使い、タイトルを動的に変えられるようにする
- CSSを切り出して、custom.scss(他のコントローラで使いそうなCSSを置くファイル), static_page.scss(StaticPagesコントローラでしか使わないCSSを置くファイル)に分けて保存。
- app/assets/stylesheets/application.scssから、Topページに関わるCSSをstatic_page.scssに移動

## 対象ページ・箇所
Stylesheets:
app/assets/stylesheets/application.scss
app/assets/stylesheets/static_page.scss
app/assets/stylesheets/custom.scss

Controller: StaticPages
Action: purchase_completed
URL: /purchase_completed 

## 重点的に見てほしいところ(不安なところ)

- cusstom.scssに、そのままそれぞれのモックアップタスクのメディアクエリ(@media)を残しています。これを一緒にすると後から他の動的ページを実装する際にCSSがわかりづらくなると思って残していますが、これでいいでしょうか。

## 解決できなかった点

2020-12-20 00:43 UTC, yuki-tachi0219 requested changes
レビューいたしました。
相談も含めていろいろ書いてしまいました。ご確認のほどお願いいたします。

2020-12-20 00:43 UTC, yuki-tachi0219 commented on app/views/static_pages/purchase_completed.html.erb
> +    <%# 注文番号を表示させる部分は、注文詳細のテーブルが作成されてから変更する %>
コメントアウトいいですね 👍 
これでエラーが起きていないのであれば、これでOKです。

2020-12-20 00:43 UTC, yuki-tachi0219 commented on app/views/static_pages/purchase_completed.html.erb
> +<div class="container">
ファイルの１行目で、ページタイトルを設定して下さい。`provide`メソッドを使えばできるかと思います。

2020-12-20 00:43 UTC, yuki-tachi0219 commented on app/helpers/application_helper.rb
> +      page_title + " | " + base_title
この部分をリファクタリングする課題をtrelloで作成しておいていただけますか？
  「式展開の方がよりよい書き方のため変更すること。なぜ式展開の方がいいのかも説明できるように」的な感じで

2020-12-20 00:43 UTC, yuki-tachi0219 commented on app/assets/stylesheets/custom.scss
> +/* ユーザー情報修正画面 */
users_controller, products_controllerができたら、それに対応するscssに一部移動させたいですね。
どのようにチケットを切ればいいと思いますか？ 
各ページを作っていただく時に、ついでにscssの移動もしていただくことにしましょうか 🤔

2020-12-20 00:43 UTC, yuki-tachi0219 commented on app/assets/stylesheets/application.scss
> + }
このファイル、消した箇所と追加した箇所が被ってるところが多いのですが、どのような作業をされましたか？
もともと書いてあったCSSを一部削除した感じでしょうか。

2020-12-20 03:56 UTC, TAKO-zhangyu commented on app/views/static_pages/purchase_completed.html.erb
> +<div class="container">
かしこまりました。

2020-12-20 03:57 UTC, TAKO-zhangyu commented on app/assets/stylesheets/custom.scss
> +/* ユーザー情報修正画面 */
> 各ページを作っていただく時に、ついでにscssの移動もしていただくことにしましょうか 🤔
これがよいと思います！

2020-12-20 04:03 UTC, TAKO-zhangyu commented on app/assets/stylesheets/application.scss
> + }
ああ、、こうなってしまいましたか。これではGitの意味がなかったですね。以後気をつけます。
これは、失念していた作業があってコミットを戻す際に、こちらのコード全てを一旦Quiverに避難させ、コミットを戻した後に貼り付けました。
もともと全行に若干のスペースがあったものが、移し替えた際にスペースが消えてしまいました。

行った作業は、Ryojiさんに実装していただいたトップページ（ログイン後）部分のCSSを、static_pages.scssに移しただけです。

2020-12-20 04:08 UTC, TAKO-zhangyu commented on app/helpers/application_helper.rb
> +      page_title + " | " + base_title
かしこまりました。

2020-12-20 04:32 UTC, yuki-tachi0219 commented on app/assets/stylesheets/application.scss
> + }
それであれば問題なさそうですね。いい感じにGitの見た目を直すのは大変だと思うので、今回はこのままでいいですよ

2020-12-21 02:52 UTC, TAKO-zhangyu commented
修正点:
- 購入完了画面にページタイトルを設定
- ルーティングのURLが指定されていたものと異なっていたことに気づいたので修正

2020-12-21 04:51 UTC, yuki-tachi0219 approved these changes
![LGTM](https://user-images.githubusercontent.com/53440378/102740616-a0164680-4393-11eb-9b98-2fe42990d93f.jpg)

2020-12-21 04:51 UTC, merged