seedデータ作成、各モデル毎にdependent & optional オプション追加
quest-academia/qa-rails-ec-training pull request #17
Opened 2020-12-19 16:56 UTC by git-ryou2405

## 作業内容
- zipcodeの警告：rubocop: disableのコメントを書き警告を出ないようにした。
- 親要素が消えても子要素を消さないよう、dependent: :nullify オプションを設定。
- 親要素を消した後、残った子要素が持つ外部キーをnilで更新されるようbelongs_to にoptional: trueを設定。

- また、Product関連のデータも生成するようseedへ追記しました。
　※ユーザ３人、商品情報は２人に２品（計4品）を登録

## 対象ページ・箇所

## 重点的に見てほしいところ(不安なところ)

## 解決できなかった点
以下の手順でoptional: trueが効いているかrails consoleから確認したのですが、
Mysqlのエラーが出て、外部キーnilでの更新や新規登録が行えませんでした。

> ①optional: trueを設定したユーザ種別、ユーザ生成
> ②親要素であるユーザ種別を削除(destroy_all)・・・しようとしたところMysqlのエラーが表示
> ③また、外部キーnilでUser.createを実行してもMysqlのエラーが表示

対処方法を調べてみたのですが、参考になる情報がなかなか得られなかったです。
考えてみた対策として、対策必要なモデルの各外部キーがnull: falseとなっているのをnull: trueにすればいけそうな気がしております。
調べてみると以下のような記事が見つかりました。対処法にお間違い無ければモデル修正を行いますがいかがでしょうか。
https://stackoverflow.com/questions/56347603/rails-6-foreign-key-cant-be-null

2020-12-20 00:59 UTC, yuki-tachi0219 requested changes
すべてのクラスのオブジェクトをseedで作ってくださりありがとうございます。現場っぽくなってきましたね！
いくつか修正していただきたいところがあるので、ご対応のほどお願いいたします。

私もnull: trueにすればうまくいきそうだと思ってるので、その対応もお願いします。

2020-12-20 00:59 UTC, yuki-tachi0219 commented on db/seeds.rb
> +i = 1
each_with_indexを使えば、iを最初に定義したり `i+=1` を宣言する必要がなくなるので、試してみてください。
同様の箇所が2,3個あったので、そこもお願いします。

2020-12-20 00:59 UTC, yuki-tachi0219 commented on db/seeds.rb
> +cate_array.each do |category|
each文などの配列繰り返しメソッドでは、番号指定パラメータというものが使えるようになりました。
`|category|`を書かずに、`Category.create!(category_name: _1)`とだけ書けば同じように動きます。
すごくイケてる書き方なのでチャレンジしてみてください。
詳細は、「Ruby 番号指定パラメータ」でググると出てきます。

2020-12-21 09:05 UTC, git-ryou2405 commented on db/seeds.rb
> +i = 1
修正しました！（each_with_indexを使い、i+=1など宣言をなくしました）

2020-12-21 09:08 UTC, git-ryou2405 commented on db/seeds.rb
> +cate_array.each do |category|
修正しました！番号指定パラメータ凄くいいですね！

> user_array.each.with_index(1) do |(first, second, third, fourth), i|

※上記の様にeach_with_indexや%記法を使ったり混合していると番号指定パラメータが試せなかったので、ここはそのままにしています！

each_with_indexメソッドもそうですが、
こういった記法があるのを初めて知りとても勉強になりました！ありがとうございます🙇‍♂️

2020-12-21 09:11 UTC, git-ryou2405 commented
> 私もnull: trueにすればうまくいきそうだと思ってるので、その対応もお願いします。

null: trueにカラム変更したところ、
親モデルデータを削除しても、子ではnilで登録されるようになったことが確認できました:raised_hands:

2020-12-22 03:08 UTC, git-ryou2405 commented
コンパクトに記述したく少し変更を加えました🙇‍♂️

2020-12-22 03:17 UTC, yuki-tachi0219 commented on db/seeds.rb
> +i = 1
`each.with_index(1)`は初めて見たのですが、いいメソッドですね 👍

2020-12-22 03:24 UTC, yuki-tachi0219 approved these changes
![LGTM](https://user-images.githubusercontent.com/53440378/102845273-8ab32200-4450-11eb-98c7-2c0f8a48932a.jpg)

2020-12-22 03:24 UTC, merged