Orders関連のvalidation,seedsを追加
quest-academia/qa-rails-ec-training pull request #22
Opened 2020-12-28 10:56 UTC by miyukihashimoto

## 作業内容
Order関連validation,seedsを追記しました。

## 対象ページ・箇所
order.rb
order_detail.rb
product.rb
shipment_status.rb
user.rb
seeds.rb

## 重点的に見てほしいところ(不安なところ)
seedsが正しく書けているか・OrderDetailのvalidationは正しいか

## 解決できなかった点

ご確認よろしくお願いいたします。

2020-12-28 13:12 UTC, yuki-tachi0219 requested changes
いい感じですね！
order_detail 辺りで修正していただきたい箇所があります。
order1.order_details だけにコメントをしていますが、同様にorder2.order_details, order3.order_details もご対応のほどお願いいたします。

2020-12-28 13:12 UTC, yuki-tachi0219 commented on db/seeds.rb
> +  shipment_date: 1
shipment_dateは日付型(datetime型)なので、 `1`のような数字を入れても値が入らず、nilになってしまいます。
`order_date`と同じく、`Time.now`でいきましょうか ⏲️

2020-12-28 13:12 UTC, yuki-tachi0219 commented on db/seeds.rb
> +  order_detail_number: 1,
`order_detail_number`はString型なので、文字列を定義しましょうか。
1桁だけだと寂しいので、`"ABC123"`のように、アルファベットと数字を混ぜた文字列でお願いします 🙇

2020-12-29 02:41 UTC, miyukihashimoto commented on db/seeds.rb
> +  shipment_date: 1
そういうことなんですね💡
修正しました！

2020-12-29 02:42 UTC, miyukihashimoto commented on db/seeds.rb
> +  order_detail_number: 1,
修正しました！

2020-12-29 05:35 UTC, yuki-tachi0219 approved these changes
![LGTM](https://user-images.githubusercontent.com/53440378/103260973-1bef3f00-49e3-11eb-94c3-6913899257e3.png)

2020-12-29 05:35 UTC, merged