ユーザ登録失敗時のエラーメッセージ修正
quest-academia/qa-rails-ec-training pull request #24
Opened 2021-01-04 09:23 UTC by git-ryou2405

## 作業内容
ユーザー登録の失敗時に何が原因でエラーが起きているのか
カラム毎にエラーメッセージを表示するよう修正しました。
また、下記も対応しました。
・日本語化対応
・scssにエラーメッセージ用のcssを追加

## 対象ページ・箇所

## 重点的に見てほしいところ(不安なところ)
元々flashメッセージを表示していたので
今回のエラー表示とflashのエラー表示と両方表示するようなっている状態です。
こちら元々のflashメッセージを表示しないようしたほうが良いでしょうか？🙇‍♂️

![スクリーンショット 2021-01-04 18 18 45](https://user-images.githubusercontent.com/57353011/103519685-4d6f7b00-4eb9-11eb-991a-7c631df8f76d.jpg)
## 解決できなかった点

2021-01-04 10:24 UTC, yuki-tachi0219 commented on app/views/users/new.html.erb
> +  <%= render 'shared/error_messages', model: f.object %>
ここはインデントを下げる必要がありますね。下のdivタグと同じ階層なので。

2021-01-04 10:24 UTC, yuki-tachi0219 commented on app/views/shared/_error_messages.html.erb
> +</div>
このコードはif, end の中に入っているので、字下げしてください。

2021-01-04 10:27 UTC, yuki-tachi0219 requested changes
PR提出ありがとうございます。
RailsTutorialと同様の実装ができていて良い感じですね。
flashメッセージとエラーメッセージは両方出ていても構わないので、そのままで大丈夫です。

html.erbファイルのインデントだけ修正していただければと思います。

2021-01-04 10:46 UTC, git-ryou2405 commented on app/views/users/new.html.erb
> +  <%= render 'shared/error_messages', model: f.object %>
修正しました！

2021-01-04 10:46 UTC, git-ryou2405 commented on app/views/shared/_error_messages.html.erb
> +</div>
修正しました！

2021-01-04 10:47 UTC, git-ryou2405 commented
> flashメッセージとエラーメッセージは両方出ていても構わないので、そのままで大丈夫です。

かしこまりました！ありがとうございます！

2021-01-05 01:14 UTC, yuki-tachi0219 approved these changes
![LGTM](https://user-images.githubusercontent.com/53440378/103595429-be0cab00-4f3e-11eb-82d5-dbc1f369f770.png)

2021-01-05 01:14 UTC, merged