フロント＆バック　商品検索画面の実装
quest-academia/qa-rails-ec-training pull request #27
Opened 2021-01-08 18:58 UTC by git-ryou2405

## 作業内容
以下を実装しました。
・商品検索画面の実装（レスポンシブも対応）
・商品検索機能の実装（商品カテゴリ、商品名のAND検索）
・gem 'kaminari'を使用したページネーションの実装（1ページに15件まで表示）

※viewの表示で、商品カテゴリープルダウンと商品名のフォームについて
上下の位置関係が気になり上下逆にしてみました。

※seeds.rbにて商品をプラス25件ほど追加しており、記述方法も少し変更しました。
seed実行時のputs表示、rubocop実施した際の指摘をいくつか修正しています🙇‍♂️

## 対象ページ・箇所

## 重点的に見てほしいところ(不安なところ)

## 解決できなかった点

2021-01-09 07:16 UTC, yuki-tachi0219 requested changes
レビューしましたので、ご確認お願いいたします。

カテゴリー名を表示する時にN+1が起きると思います。直せそうなら直してください。半日以上かかりそうなら保留にしましょう。

2021-01-09 07:16 UTC, yuki-tachi0219 commented on app/views/products/index.html.erb
> +    <% if @products.count > 0 %>
19行目と20行目は @products.present? の一行にまとめられると思います

2021-01-09 07:16 UTC, yuki-tachi0219 commented on app/views/products/index.html.erb
> +        <%= f.collection_select :id, @categories, :id, :category_name %><br>
idだと何のidかわからないので、category_id としてください。
params[:id]は /users/1 のようにurl内で指定する際に使うことが多く、「urlでidを指定するのか？」とあらぬ誤解を招いてしまうというのも変更する理由の一つです

2021-01-09 07:16 UTC, yuki-tachi0219 commented on app/controllers/products_controller.rb
> +      flash.now[:notice] = "商品が見つかりません。" if @products.blank?
この書き方でflashメッセージ見れますか？
flash[:notice] にしないと見れないんじゃないかと思いました。
見れるならこのままでokです

2021-01-09 07:16 UTC, yuki-tachi0219 commented on app/controllers/products_controller.rb
> +    return unless params[:search_button]
fantastic! 👍

2021-01-09 07:16 UTC, yuki-tachi0219 commented on app/models/product.rb
> +    where(category_id: id).where("product_name LIKE ?", "%#{search}%")
search, id は抽象度が高すぎるので変えたいです。
それぞれproduct_name, category_id くらい具体的な名前にしたいです。

このメソッドをuserやorderなど他のモデルに使い回す時が来たら、抽象的な変数名にしましょうか。

2021-01-10 04:23 UTC, git-ryou2405 commented on app/controllers/products_controller.rb
> +      flash.now[:notice] = "商品が見つかりません。" if @products.blank?
flash.nowでメッセージ表示できております🔅
（ちなみにflash[:notice]だと更新や他pageリダイレクト表示した際、flash再度表示されてしまうので寿命問題ありますね..）

2021-01-10 04:24 UTC, git-ryou2405 commented on app/views/products/index.html.erb
> +        <%= f.collection_select :id, @categories, :id, :category_name %><br>
category_id へ修正しました！

2021-01-10 04:24 UTC, git-ryou2405 commented on app/views/products/index.html.erb
> +    <% if @products.count > 0 %>
修正しました！presentそうですね🙇‍♂️

2021-01-10 04:24 UTC, git-ryou2405 commented on app/views/products/index.html.erb
> +              <td><%= Category.find(product.category_id).category_name %></td>
こういった書き方で取得できるのですね😶　修正しました！

2021-01-10 04:24 UTC, git-ryou2405 commented on app/models/product.rb
> +    where(category_id: id).where("product_name LIKE ?", "%#{search}%")
そうですね、ありがとうございます！
search_product、category_id としました。

2021-01-10 04:29 UTC, git-ryou2405 commented
> カテゴリー名を表示する時にN+1が起きると思います。直せそうなら直してください。半日以上かかりそうなら保留にしましょう。

こちら商品検索画面を表示時のログ確認したのですが、
SQLは１行だけしか発行されていないように見えており
N+1問題が起きているのがよく理解できておりません、、
ご教示いただけますと幸いです🙇‍♂️
```
web_1  | Started GET "/products" for 172.18.0.1 at 2021-01-10 03:51:00 +0000
web_1  | Cannot render console from 172.18.0.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
web_1  | Processing by ProductsController#index as HTML
web_1  |   Rendering products/index.html.erb within layouts/application
web_1  |   Category Load (0.9ms)  SELECT DISTINCT `categories`.* FROM `categories` INNER JOIN `products` ON `products`.`category_id` = `categories`.`id` WHERE `products`.`category_id` IS NOT NULL
web_1  |   ↳ app/views/products/index.html.erb:9
web_1  |   Rendered products/index.html.erb within layouts/application (Duration: 18.9ms | Allocations: 4711)
web_1  | [Webpacker] Everything's up-to-date. Nothing to do
web_1  |   User Load (1.1ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 2 LIMIT 1
web_1  |   ↳ app/helpers/sessions_helper.rb:10:in `current_user'
web_1  |   Rendered layouts/_header.html.erb (Duration: 48.5ms | Allocations: 11539)
web_1  |   Rendered layouts/_footer.html.erb (Duration: 0.1ms | Allocations: 32)
web_1  | Completed 200 OK in 157ms (Views: 106.0ms | ActiveRecord: 29.5ms | Allocations: 28054)
```

↓この部分が問題でしょうか？
```
web_1  |   Category Load (0.9ms)  SELECT DISTINCT `categories`.* FROM `categories` INNER JOIN `products` ON `products`.`category_id` = `categories`.`id` WHERE `products`.`category_id` IS NOT NULL
```

2021-01-10 05:34 UTC, git-ryou2405 commented
> カテゴリー名を表示する時にN+1が起きると思います。直せそうなら直してください。半日以上かかりそうなら保留にしましょう。

each内で検討するとN+1となってしまいそうでしたので
先にcontroller側でcategory_nameを取得してインスタンス変数に格納し
そのインスタンス変数を利用するよう対策してみましたがいかがでしょうか🙏

> @category_name = Category.find(params[:category_id]).category_name

2021-01-12 01:02 UTC, yuki-tachi0219 commented on app/models/product.rb
> +    where(category_id: id).where("product_name LIKE ?", "%#{search}%")
search_productだとまだ抽象的ですねー
「商品の名前をキーワードにしている」ということをアピールしたいので、name は入れたいです

2021-01-12 12:51 UTC, git-ryou2405 commented on app/models/product.rb
> +    where(category_id: id).where("product_name LIKE ?", "%#{search}%")
かしこまりました！search_product_nameへ修正しました🙏

2021-01-12 12:52 UTC, git-ryou2405 commented
N+1の件について、Product.includes(:category)の方法へ修正いたしました。
ご確認の程よろしくお願いいたします🙇‍♂️

2021-01-12 13:04 UTC, yuki-tachi0219 approved these changes
![LGTM](https://user-images.githubusercontent.com/53440378/104317941-0a00b680-5522-11eb-8e26-ae4f6479c4e5.gif)

2021-01-12 13:04 UTC, merged