Feature/manjumoto/products detail
quest-academia/qa-rails-ec-training pull request #29
Opened 2021-01-12 12:13 UTC by daishiman

## 作業内容
* products の show メソッド実装

## 対象ページ・箇所

## 重点的に見てほしいところ(不安なところ)

## 解決できなかった点

2021-01-12 13:10 UTC, yuki-tachi0219 commented on app/views/products/show.html.erb
> +        </div>
ここは link_toを使いましょう。
商品検索画面がマージされたので、商品検索画面に遷移するように設定してください。

2021-01-12 13:11 UTC, yuki-tachi0219 commented on app/views/products/show.html.erb
> +            <%= f.submit "カートへ", class: "btn btn-lg btn-primary" %>
この部分インデントが右にずれているので直しておいてください。

2021-01-12 13:13 UTC, yuki-tachi0219 commented on app/controllers/products_controller.rb
> +  # end
この部分は他の方が作ってくれるところなので、消しておきましょう。
コメントが残ってるとコンフリクトが起きてしまいます。

2021-01-12 13:24 UTC, yuki-tachi0219 requested changes
レビューいたしましたので、ご確認のほどお願いいたします。

コードの見やすさという観点から、コメントはなるべく消したほうがいいです。  
「コード読めばわかるんだから、コメントは要らないよね」というのが基本思想です。  
コメントがなくても問題なく読めるコードを書くことが理想ですが、初心者がいきなり実行するのは難しいので、難しいロジックにだけコメントを書いていきましょう。

コメントが必要かどうか判断する目安としては、
• コードの直訳でしかないコメントは不要
   • 例: `validates :name, presence: true #nameカラムは値が入ってないといけない`← コメント不要！
• 複雑すぎるロジックの場合はコメントをしてもいい(今回はそこまで複雑ではないので不要)
• なぜこのコードを書いたのか、という理由はコメントしてもいい
   •例: `if self.send_type_issuance? #送金タイプが"発行"の場合は新たにコインを生み出す処理のため、残高チェックをしない`←コメントOK

2021-01-13 02:33 UTC, yuki-tachi0219 commented on app/views/products/index.html.erb
> +              <%= button_to "商品詳細", product_path(product), method: :get, class:"btn btn-sm btn-primary my-auto" %>
`method: :get` を消してもうまく動く気がするのですが、試していただけますでしょうか 🙏

2021-01-13 03:05 UTC, yuki-tachi0219 requested changes
Rubyの構文はいい感じですね！
html, css の指摘になっていしまい恐縮ですが、修正お願いいたします。

2021-01-13 03:05 UTC, yuki-tachi0219 commented on app/views/products/show.html.erb
> +<div class="container-fluid">
5行目でcontainer-fluidを定義しているのでこの行は不要ですね。
削除してインデントを合わせておいてください。

2021-01-13 03:05 UTC, yuki-tachi0219 commented on app/views/products/show.html.erb
> +  <div class="container-fluid text-center">
container-fluid → container
に修正お願いします。 両端に余白を作りたかったので。

2021-01-13 03:05 UTC, yuki-tachi0219 commented on app/views/products/show.html.erb
> +      <% end %>
モックアップを参考にすると、10~24行目はh2タグで囲まれてますね。
h2タグだと文字が大きすぎるので、
10~24行目をh4タグで囲っていただけますでしょうか。

2021-01-14 01:21 UTC, daishiman commented on app/views/products/show.html.erb
> +<div class="container-fluid">
修正しました。

2021-01-14 01:23 UTC, daishiman commented on app/views/products/show.html.erb
> +  <div class="container-fluid text-center">
承知しました。

container に文字が納まっていなかったので文字の大きさ変更うしました。

2021-01-14 01:24 UTC, daishiman commented on app/views/products/show.html.erb
> +      <% end %>
修正しました。

2021-01-14 02:25 UTC, daishiman commented
レビュー頂いた内容と rubocop で指摘された内容を修正しましたが、一部そのままにしています。

* app/controllers/users_controller.rb:28:14: W: Rails/ActiveRecordAliases: Use update instead of update_attributes.
    if @user.update_attributes(user_params)
update_attributes と update は別の動きをするといううことから修正なし

* app/helpers/application_helper.rb:7:7: C: Style/StringConcatenation: Prefer string interpolation to string concatenation.
      page_title + " | " + base_title
こちらの修正対応は解らなかったのでそのままにしています。
すみません。

2021-01-14 05:44 UTC, yuki-tachi0219 commented
rubocop についてのご報告ありがとうございます。
設定ファイルの変更内容もOKです。
> app/controllers/users_controller.rb:28:14: W: Rails/ActiveRecordAliases: Use update instead of update_attributes.

updateとupdate_attributesは、全く同じ動きをするメソッドです。
「updateに統一しようね」という指摘ですね。今回のチケットではしなくて大丈夫です。

>app/helpers/application_helper.rb:7:7: C: Style/StringConcatenation: Prefer string interpolation to string concatenation.

こちらはtrelloで別途チケットを作ってあるので対応不要です。

2021-01-14 05:45 UTC, yuki-tachi0219 approved these changes
![LGTM](https://user-images.githubusercontent.com/53440378/104549941-219d8380-5677-11eb-8e81-f702d469a541.jpeg)

2021-01-14 05:45 UTC, merged