Feature/hashimoto/order detail page
quest-academia/qa-rails-ec-training pull request #30
Opened 2021-01-13 08:42 UTC by miyukihashimoto

## 作業内容
・ルーティング・URLの設定
・paramsから情報を取ってきて表示
・「注文をキャンセルする」ボタンは注文状態に「準備中」のものがあれば表示
・合計は全ての商品の小計を足して表示する
・「注文履歴に戻る」ボタンを実装する
・検索結果がみつからなかった際のページを表示

## 対象ページ・箇所
orders_controller.rb
helpers/orders_helper.rb
views/orders/blank.html.erb -> app/views/orders/_blank.html.erb
views/orders/show.html.erb

## 重点的に見てほしいところ(不安なところ)
・注文キャンセルボタンが正しく実装されているか
・合計の処理は合っているか

## 解決できなかった点

2021-01-14 06:34 UTC, yuki-tachi0219 requested changes
目的の動きはだいたいできていますね！！
ヘルパーも使われていていい感じです 👍 

より良い書き方にするために、数点修正お願いします。

2021-01-14 06:34 UTC, yuki-tachi0219 commented on app/helpers/orders_helper.rb
> +      end
この部分は、
`["入荷待ち","入荷待ち","準備中"]`という配列を作るのが目的ですよね？
これだと最後のorder_detailだけが@arrayに入り、しかも@arrayが配列ではなくなってしまいます。
`@array << order_detail. ....` と書けば目的の動きになります。

Helperに分ける方針、すばらしいですね！！
せっかくヘルパーに分けているので、viewに書いてあるコードをここに移植したいと思います。
「@arrayに"準備中"が含まれていたらボタンを出す」という箇所をそのままここに書きます。
以下のようなイメージです。

①まず、上記の指摘を修正。
②buttonタグをlink_toに置き換え、ヘルパーのcancel_button_indicateに以下を追記

```
if @array.include?("準備中")
  link_to "注文履歴に戻る", "#", class: "btn btn-danger"
end
```

③show.html.erbの部分は、
```
<div class="my-4 text-right">
   <% cancel_button_indicate %>
</div>
```
これだけでよくなります。

④helperは、本来viewに書くロジックを分離するためのものです。orders_controller.rbにcancel_button_indicateは書かなくてOKです。

⑤これで、html.erbで@arrayを使わなくなりました。このヘルパー内でしか@arrayを使っていないので、ローカル変数arrayにしましょう。

2021-01-14 06:34 UTC, yuki-tachi0219 commented on app/views/orders/_blank.html.erb
> +<% provide(:title, "blank") %>
タイトルは、"該当注文なし"にしておいてください

2021-01-14 06:34 UTC, yuki-tachi0219 commented on app/controllers/orders_controller.rb
> +    end
このあたりのロジックも変えないといけないですね。
コントローラでrenderする時は、ファイルにアンダーバーを付けてはいけないみたいで、これだとうまく表示できないです。私の認識が間違えていてすみません。

ここの条件分岐は意外と複雑なので、ペアプロでご説明したいです。

2021-01-14 08:15 UTC, miyukihashimoto commented on app/controllers/orders_controller.rb
> +      end
sumを自分で調べた際、
Book.all.sum(:price)
のような書き方ができると知ったのですが実装できずでした😭
今は少し複雑に感じますが、このようにすれば良いんですね✨

2021-01-14 09:12 UTC, miyukihashimoto commented on app/views/orders/_blank.html.erb
> +<% provide(:title, "blank") %>
修正しました。

2021-01-14 09:36 UTC, miyukihashimoto commented on app/helpers/orders_helper.rb
> +      end
修正しました！

2021-01-14 09:46 UTC, miyukihashimoto commented on app/controllers/orders_controller.rb
> +    end
ordersコントローラーで
render "_blank"
としたら読み込みできるようになりましたので、修正しています。

2021-01-15 03:26 UTC, yuki-tachi0219 commented
コンフリクト対応だけお願いいたします 🙏

2021-01-15 04:12 UTC, yuki-tachi0219 commented on db/seeds.rb
> -shipment_status2 = ShipmentStatus.create!(shipment_status_name: "準備中")
準備中のShipmentStatusはほしいので、消さずに残しておいてください。
入荷待ち→準備中の順でデータを作るようお願いします。

2021-01-15 04:14 UTC, yuki-tachi0219 commented on db/seeds.rb
> +)
order_detailsを複数作る部分は、みゆきさんの作業内容の方を優先していただければと思います。
shipment_status_id: 2 のデータを作って、注文キャンセルボタンが表示されるパターンも用意したいので。

2021-01-15 04:45 UTC, miyukihashimoto commented on db/seeds.rb
> -shipment_status2 = ShipmentStatus.create!(shipment_status_name: "準備中")
修正しました。

2021-01-15 04:48 UTC, miyukihashimoto commented on db/seeds.rb
> +)
すみません、消してしまってました。。
修正済みです。

2021-01-15 05:00 UTC, yuki-tachi0219 approved these changes
![LGTM](https://user-images.githubusercontent.com/53440378/104683315-021b5f00-573a-11eb-9df2-beb226e5738a.png)

2021-01-15 05:00 UTC, merged