Feature/manjumoto/authorization
quest-academia/qa-rails-ec-training pull request #33
Opened 2021-01-18 02:20 UTC by daishiman

## 作業内容
* 認可機能の実装
  * ログイン済みユーザーかどうか確認
  * 正しいユーザーかどうか確認
* rubocop 実装
  * Time.now → Time.zone.now 
  * shipment_status, shipment_status2 の変数設定しているが、変数を使っていないので非表示
 
* header のユーザ情報のリンク実装

## 対象ページ・箇所
* app/controllers/orders_controller.rb
* app/controllers/sessions_controller.rb
* app/controllers/users_controller.rb
* app/helpers/orders_helper.rb
* app/helpers/sessions_helper.rb
* app/views/layouts/_header.html.erb
* db/seeds.rb

## 重点的に見てほしいところ(不安なところ)
* rubocop にて helper でインスタンス変数を使うのはだめよと注意されていますが、インスタンス変数は必要と思いそのままにしています。

## 解決できなかった点  

ご確認保ほどよろしくお願い致します。

2021-01-18 17:27 UTC, yuki-tachi0219 requested changes
いい感じです！素晴らしいですね ✨ 
機能を追加していただきたいところと、現時刻表示メソッドについて修正していただきたく思います

2021-01-18 17:27 UTC, yuki-tachi0219 commented on db/seeds.rb
> +  shipment_date: Time.zone.now,
現時刻を求める時は、`Time.current`を使いたいです。
Time.zone.now と Time.currentの違いを調査してみてください 👀

2021-01-18 17:27 UTC, yuki-tachi0219 commented on app/controllers/orders_controller.rb
>      @order = Order.find_by(id: params[:id])
すみません。私が見落としていたところなのですが、
Orders#showは、「ログインしたユーザーに関する注文の中から、idがparams[:id]のものを取ってくる」
という動きにしたいです。indexも同様に、ログインユーザーに紐づく注文だけとってきたいですね。
この行を修正していただけますでしょうか 🙏 

また、この修正のやり方が分かったら、注文一覧に取り組んでいる方にこの旨伝えていただきたいです。

2021-01-20 02:59 UTC, daishiman commented on db/seeds.rb
> +  shipment_date: Time.zone.now,
修正しました

2021-01-20 03:01 UTC, daishiman commented on app/controllers/orders_controller.rb
>      @order = Order.find_by(id: params[:id])
修正しました。

ご確認の程よろしくおねがいします。

2021-01-20 03:12 UTC, yuki-tachi0219 commented on app/controllers/orders_controller.rb
>      @order = Order.find_by(id: params[:id])
これだとエラー起きませんか？
`Order`の部分を変更しないといけないですね。
current_userに紐づくorderという形にしたいです。

2021-01-20 04:20 UTC, daishiman commented on app/controllers/orders_controller.rb
>      @order = Order.find_by(id: params[:id])
アドバイス有難うございます。
修正いたしました。

ご確認の程よろしくお願い致します。

2021-01-20 05:53 UTC, yuki-tachi0219 commented on app/controllers/orders_controller.rb
>      @order = Order.find_by(id: params[:id])
いい感じです 👍

2021-01-20 05:54 UTC, yuki-tachi0219 approved these changes
![LGTM](https://user-images.githubusercontent.com/53440378/105133052-5609b780-5b2f-11eb-8f1e-d1400cbef4e9.png)

2021-01-20 05:54 UTC, merged