READMEにDocker操作を追記
quest-academia/qa-rails-ec-training pull request #6
Opened 2020-12-04 02:28 UTC by git-ryou2405

## 作業内容
READMEにDocker操作を追記しました。
内容は今回向けに書き換えてみました。

ご確認のほどよろしくお願いいたします:pray:

## 対象ページ・箇所

## 重点的に見てほしいところ(不安なところ)

## 解決できなかった点

2020-12-04 06:42 UTC, yuki-tachi0219 requested changes
レビューいたしました。
yarn installの話も入れてくださりありがとうございます！！
以下、修正していただきたく思います。

2020-12-04 06:42 UTC, yuki-tachi0219 commented on README.md
> +以下の方法で、yarnをインストールしてください。（約5分）
`Ctrl + Cでコンテナを停止し、`という文言を一応ここにも入れておきましょうか

2020-12-04 06:42 UTC, yuki-tachi0219 commented on README.md
> +```
「dockerのログが出っぱなしになるから、以下のコマンドを実行する時は別のターミナルを開いてね」という文言をお願いします 🙇

2020-12-04 06:42 UTC, yuki-tachi0219 commented on README.md
> +```
今回は、コンテナに入らないやり方にしましょうか。
- コンテナに入るの忘れて`bundle install`を実行すると面倒なことになる
- たぶんエイリアスが使えない

ことが理由です。
`docker-compose exec web bundle install`, `docker-compose exec web bundle exec rails db:migrate` のような書き方でお願いします。

2020-12-04 10:44 UTC, git-ryou2405 commented on README.md
> +以下の方法で、yarnをインストールしてください。（約5分）
修正しました！

2020-12-04 10:44 UTC, git-ryou2405 commented on README.md
> +```
文言を加えました！

2020-12-04 10:44 UTC, git-ryou2405 commented on README.md
> +```
確かに危険ですね💦　入らない方法に書き換えました！

2020-12-04 23:55 UTC, yuki-tachi0219 commented on README.md
> +```
docker-compose exec web bundle exec rails db:migrate のように、間にbundle exec を入れてください 🙏

2020-12-05 02:44 UTC, git-ryou2405 commented on README.md
> +```
修正いたしました:pray:
（bundle execについて記事を色々読みましたが要不要の判断が曖昧なままです..）

2020-12-06 09:17 UTC, yuki-tachi0219 commented on README.md
> +```
`docker-compose exec web rails db:create`
ここも修正お願いします 🙏 

bundle execが必要な理由は、この記事がわかりやすいですかねー
https://qiita.com/diskkid/items/0d000a42df04c561ca0f
基本的には、「すべての場合で bundle execを付ける」でOKです。

2020-12-06 10:21 UTC, git-ryou2405 commented on README.md
> +```
修正いたしました:pray:　承知しました！ありがとうございます！

2020-12-06 10:25 UTC, yuki-tachi0219 approved these changes
<img width="766" alt="LGTM" src="https://user-images.githubusercontent.com/53440378/101277573-b4d1d680-37f8-11eb-9d47-78fe795e30e4.png">

2020-12-06 10:25 UTC, merged